# Setting up docker packages like docker-ce and docker-compose
---
- name: Update apt
  apt:
    update_cache: yes

- name: Get apt package facts
  package_facts:
    manager: "auto"

- name: Install required system packages
  apt:
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

- name: Add docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: '"docker-ce" not in ansible_facts.packages'

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when: '"docker-ce" not in ansible_facts.packages'

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
  when: '"docker-ce" not in ansible_facts.packages'

- name: Install docker-compose
  apt:
    name: docker-compose
    state: latest
  when: '"docker-compose" not in ansible_facts.packages'

- name: Install Docker Module for Python
  pip:
    name: docker
  when: '"docker" not in ansible_facts.packages'
