---
# tasks file for install
#
- name: Update apt-get repo
  ansible.builtin.apt:
    update_cache: true

- name: install base packages
  ansible.builtin.apt:
    state: latest
    pkg:
      - software-properties-common
      - curl
      - vim
      - nfs-common

- name: Add Hashicorp GPG apt key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp Linux Repository
  ansible.builtin.apt_repository:
    repo: >-
      deb https://apt.releases.hashicorp.com
      {{ ansible_distribution_release | lower }} main
    state: present
