# Create policy and token for nodes
- name: Copy node-policy.hcl to temp
  copy:
    src: tmp/node-policy.hcl
    dest: /tmp/node-policy.hcl

- name: Create policy using node-policy
  command:
    cmd: "consul acl policy create  -token={{ consul_global_management_token }} -http-addr={{ ansible_default_ipv4.address}}:8500 -name node-policy -rules @/tmp/node-policy.hcl"

- name: Create token using node-policy
  command:
    cmd: "consul acl token create -token={{ consul_global_management_token }}  -http-addr={{ ansible_default_ipv4.address}}:8500 -description \"node token\" -policy-name node-policy -format=json"
  register: _consul_token_output

- name: Extract node-policy token from output
  set_fact:
    consul_node_token: "{{ _consul_token_output.stdout | from_json | json_query('SecretID') }}"

- name: Saved token to vars/consul/node-token.yaml (local)
  template:
    src: local/vars/consul/node-token.yaml.j2
    dest: '{{ role_path }}/vars/consul/node-token.yaml'
    mode: 0640
  delegate_to: localhost
  become: no
  become_user: "{{ lookup('env', 'USER') }}"
