# Setting up docker packages like docker-ce and docker-compose
---

- name: Check if JumpCloud is already installed
  shell: "[ -d /opt/jc ] && echo 'Found' || echo ''"
  register: jc_installed

- name: Update time
  shell: "ntpdate -u pool.ntp.org"
  when: "not jc_installed.stdout"
  ignore_errors: yes

- name: Install JumpCloud
  shell: "curl --header 'x-connect-key: {{ connect_key }}' https://kickstart.jumpcloud.com/Kickstart | sudo bash"
  when: "not jc_installed.stdout"
