# Install all base packages we need
---
- name: Update apt-get repo and cache
  apt:
    update_cache: true

- name: install base packages
  apt:
    state: latest
    pkg:
      - software-properties-common
      - ntpdate
      - unzip
      - zip
      - git
      - curl
      - vim
      - tmux

- name: Apply global vim settings
  copy:
    src: etc/vim/vimrc.local
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: '0644'
