---
collections:
  - name: community.general
    version: 7.0.0
    source: https://galaxy.ansible.com
  - name: community.hashi_vault
    version: 5.0.1
    source: https://galaxy.ansible.com
  - name: git+https://github.com/veloslab/ansible-ee.git#/collections/
