# Installing Python Venv
---
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install software-properties-common
  ansible.builtin.apt:
    state: present
    pkg:
      - software-properties-common

- name: Add deadsnakes/ppa Repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install Python (base)
  ansible.builtin.apt:
    pkg:
      - 'python{{ python_venv_version }}'
      - 'python{{ python_venv_version }}-distutils'
      - 'python{{ python_venv_version }}-venv'
      - 'python{{ python_venv_version }}-dev'
    state: present

- name: Create Python Virtual Env
  ansible.builtin.pip:
    virtualenv: '/veloslab/python/{{ python_venv_name }}_{{ python_venv_version }}'
    virtualenv_command: 'python{{ python_venv_version }} -m venv'
    name: "{{ python_venv_packages | default(omit) }}"
    requirements: "{{ python_venv_requirements | default(omit) }}"

- name: Create a Symbolic link for Python Virtual Env
  ansible.builtin.file:
    src: '/veloslab/python/{{ python_venv_name }}_{{ python_venv_version }}'
    dest: '/veloslab/python/{{ python_venv_name }}'
    owner: root
    group: root
    state: link
    mode: 0755
