# Workflow name
name: Veloslab EE build


# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:

      # In this job, all steps begin with a name
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        
      - name: Install python requirements (ansible-builder)
        run: pip install ansible-builder==3.0.0

      - name: Build image
        id: build-image
        run: |
          ansible-builder build --container-runtime=docker --verbosity 3 
